alias lf='ls -AF'
alias ll='ls -lAF'
alias wrenv='/c/windriver/wrenv.sh -p vxworks-6.3'
alias wrmake='wrenv make -C PPC603gnu'
alias deploy='wput -v Balance.out ftp://10.14.25.2/ni-rt/system/FRC_UserProgram.out'
alias undeploy='wdel -v ftp://10.14.25.2/ni-rt/system/FRC_UserProgram.out'
